name: Send Annual Email

on:
  schedule:
    - cron: '0 0 1 1 *'  # This cron job runs at 00:00 on January 1st every year

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ssmtp
        echo "root=$EMAIL" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthUser=$EMAIL" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthPass=$EMAIL_PASSWORD" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "UseSTARTTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "FromLineOverride=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "To: 19126@sevenkings.school" > email.txt
        echo "From: $EMAIL" >> email.txt
        echo "Subject: User:CGRoffcialcode" >> email.txt
        echo "" >> email.txt
        echo "Remember to keep track of this as a mp4 in your GitHub account!" >> email.txt
        echo "<https://git-wrapped.com/>" >> email.txt
        ssmtp 19126@sevenkings.school < email.txt
